/*
ONE CARGO TRACKING API

Cargo tacking details is provided based on DCSA standards. (1.2)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package one

import (
	"encoding/json"
)

// SampleEvent struct for SampleEvent
type SampleEvent struct {
	Events *[]interface{} `json:"events,omitempty"`
}

// NewSampleEvent instantiates a new SampleEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSampleEvent() *SampleEvent {
	this := SampleEvent{}
	return &this
}

// NewSampleEventWithDefaults instantiates a new SampleEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSampleEventWithDefaults() *SampleEvent {
	this := SampleEvent{}
	return &this
}

// GetEvents returns the Events field value if set, zero value otherwise.
func (o *SampleEvent) GetEvents() []interface{} {
	if o == nil || o.Events == nil {
		var ret []interface{}
		return ret
	}
	return *o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SampleEvent) GetEventsOk() (*[]interface{}, bool) {
	if o == nil || o.Events == nil {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *SampleEvent) HasEvents() bool {
	if o != nil && o.Events != nil {
		return true
	}

	return false
}

// SetEvents gets a reference to the given []interface{ and assigns it to the Events field.
func (o *SampleEvent) SetEvents(v []interface{}) {
	o.Events = &v
}

func (o SampleEvent) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Events != nil {
		toSerialize["events"] = o.Events
	}
	return json.Marshal(toSerialize)
}

type NullableSampleEvent struct {
	value *SampleEvent
	isSet bool
}

func (v NullableSampleEvent) Get() *SampleEvent {
	return v.value
}

func (v *NullableSampleEvent) Set(val *SampleEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableSampleEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableSampleEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSampleEvent(val *SampleEvent) *NullableSampleEvent {
	return &NullableSampleEvent{value: val, isSet: true}
}

func (v NullableSampleEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSampleEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


