/*
ONE Specification for DCSA Track & Trace API v2.2

  # DCSA Track and Trace v2.2    **Overview:**    The **DCSA Track and Trace v2.2 API** provides a standardized and reliable mechanism for tracking container movements throughout the global shipping network. It is designed to align with the Digital Container Shipping Association (DCSA) standards, promoting **interoperability** between carriers, shippers, and third-party logistics providers.    This API allows stakeholders to monitor the **end-to-end journey** of containers, offering insights into key milestones such as:  - **Vessel arrivals**  - **Departures**  - **Equipment loading**  - **Transport events**    By delivering **uniform tracking data** across various carriers and ports, this API reduces manual processes and improves operational efficiency for managing large-scale shipping operations.    ---    ## Key Features:    ### 1. **Event Standardization**    All events related to container transport are defined according to DCSA standards, ensuring consistent terminology and reporting across the entire logistics chain.    ### 2. **On-Demand Data Retrieval**    Customers can pull **up-to-date information** about container locations, equipment status, and shipment events when needed, enabling timely and informed decision-making.    ### 3. **Seamless Integration**    Designed to integrate easily with existing systems, the API offers flexibility for users who manage large-scale shipments or have evolving logistics requirements.    ### 4. **Scalability**    Whether tracking a few containers or managing thousands, the API is optimized to handle **large datasets efficiently**, ensuring timely access to critical shipping information.    ---    ### Conclusion:    The **DCSA Track and Trace v2.2 API** empowers companies to enhance their visibility into global logistics operations, improve communication between parties, and drive better service outcomes through transparency and **real-time information sharing**.

API version: 2.2
Contact: integration.support@one-line.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package one

import (
	"encoding/json"
	"fmt"
)

// TransportEventTypeCode Identifier for type of Transport event - ARRI (Arrived) - DEPA (Departed)  More details can be found on <a href=\"https://github.com/dcsaorg/DCSA-Information-Model/blob/master/datamodel/referencedata.d/transporteventtypecodes.csv\">GitHub</a>
type TransportEventTypeCode string

// List of transportEventTypeCode
const (
	ARRI TransportEventTypeCode = "ARRI"
	DEPA TransportEventTypeCode = "DEPA"
)

// All allowed values of TransportEventTypeCode enum
var AllowedTransportEventTypeCodeEnumValues = []TransportEventTypeCode{
	"ARRI",
	"DEPA",
}

func (v *TransportEventTypeCode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TransportEventTypeCode(value)
	for _, existing := range AllowedTransportEventTypeCodeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TransportEventTypeCode", value)
}

// NewTransportEventTypeCodeFromValue returns a pointer to a valid TransportEventTypeCode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTransportEventTypeCodeFromValue(v string) (*TransportEventTypeCode, error) {
	ev := TransportEventTypeCode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TransportEventTypeCode: valid values are %v", v, AllowedTransportEventTypeCodeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TransportEventTypeCode) IsValid() bool {
	for _, existing := range AllowedTransportEventTypeCodeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to transportEventTypeCode value
func (v TransportEventTypeCode) Ptr() *TransportEventTypeCode {
	return &v
}

type NullableTransportEventTypeCode struct {
	value *TransportEventTypeCode
	isSet bool
}

func (v NullableTransportEventTypeCode) Get() *TransportEventTypeCode {
	return v.value
}

func (v *NullableTransportEventTypeCode) Set(val *TransportEventTypeCode) {
	v.value = val
	v.isSet = true
}

func (v NullableTransportEventTypeCode) IsSet() bool {
	return v.isSet
}

func (v *NullableTransportEventTypeCode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransportEventTypeCode(val *TransportEventTypeCode) *NullableTransportEventTypeCode {
	return &NullableTransportEventTypeCode{value: val, isSet: true}
}

func (v NullableTransportEventTypeCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransportEventTypeCode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
