/*
ONE CARGO TRACKING API

Cargo tacking details is provided based on DCSA standards. (1.2)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package one

import (
	"encoding/json"
)

// TransportEquipmentEventAllOf struct for TransportEquipmentEventAllOf
type TransportEquipmentEventAllOf struct {
	EventType *string `json:"eventType,omitempty"`
	// The reference for the transport, e.g. when the mode of transport is a vessel, the transport reference will be the vessel IMO number.
	TransportReference string `json:"transportReference"`
	// The transport leg reference will be specific per mode of transport: - Vessel: Voyage number as specified by the vessel operator - Truck: Not yet specified - Rail: Not yet specified - Barge: Not yet specified. 
	TransportLegReference string `json:"transportLegReference"`
	// The unique identifier for the equipment, which should follow the BIC ISO Container Identification Number where possible. If a container is not yet assigned to a shipment, the interface cannot return any information when an equipment reference is given as input. If a container is assigned to an (active) shipment, the interface returns information on the active shipment.
	EquipmentReference *string `json:"equipmentReference,omitempty"`
	// The code to identify the specific type of facility.
	FacilityTypeCode string `json:"facilityTypeCode"`
	// The UN Location Code identifies a location in the sense of a city/a town/a village, being the smaller administrative area existing as defined by the competent national authority in each country.
	UNLocationCode string `json:"UNLocationCode"`
	// The code used for identifying the specific facility.
	FacilityCode string `json:"facilityCode"`
	// An alternative way to capture the facility when no standardized DCSA facility code can be found.
	OtherFacility *string `json:"otherFacility,omitempty"`
	// Code to denote whether the equipment is empty or laden.
	EmptyIndicatorCode string `json:"emptyIndicatorCode"`
	// A code specifying a type of transport mode.
	ModeOfTransportCode *int32 `json:"modeOfTransportCode,omitempty"`
}

// NewTransportEquipmentEventAllOf instantiates a new TransportEquipmentEventAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransportEquipmentEventAllOf(transportReference string, transportLegReference string, facilityTypeCode string, uNLocationCode string, facilityCode string, emptyIndicatorCode string) *TransportEquipmentEventAllOf {
	this := TransportEquipmentEventAllOf{}
	this.TransportReference = transportReference
	this.TransportLegReference = transportLegReference
	this.FacilityTypeCode = facilityTypeCode
	this.UNLocationCode = uNLocationCode
	this.FacilityCode = facilityCode
	this.EmptyIndicatorCode = emptyIndicatorCode
	return &this
}

// NewTransportEquipmentEventAllOfWithDefaults instantiates a new TransportEquipmentEventAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransportEquipmentEventAllOfWithDefaults() *TransportEquipmentEventAllOf {
	this := TransportEquipmentEventAllOf{}
	return &this
}

// GetEventType returns the EventType field value if set, zero value otherwise.
func (o *TransportEquipmentEventAllOf) GetEventType() string {
	if o == nil || o.EventType == nil {
		var ret string
		return ret
	}
	return *o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportEquipmentEventAllOf) GetEventTypeOk() (*string, bool) {
	if o == nil || o.EventType == nil {
		return nil, false
	}
	return o.EventType, true
}

// HasEventType returns a boolean if a field has been set.
func (o *TransportEquipmentEventAllOf) HasEventType() bool {
	if o != nil && o.EventType != nil {
		return true
	}

	return false
}

// SetEventType gets a reference to the given string and assigns it to the EventType field.
func (o *TransportEquipmentEventAllOf) SetEventType(v string) {
	o.EventType = &v
}

// GetTransportReference returns the TransportReference field value
func (o *TransportEquipmentEventAllOf) GetTransportReference() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransportReference
}

// GetTransportReferenceOk returns a tuple with the TransportReference field value
// and a boolean to check if the value has been set.
func (o *TransportEquipmentEventAllOf) GetTransportReferenceOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.TransportReference, true
}

// SetTransportReference sets field value
func (o *TransportEquipmentEventAllOf) SetTransportReference(v string) {
	o.TransportReference = v
}

// GetTransportLegReference returns the TransportLegReference field value
func (o *TransportEquipmentEventAllOf) GetTransportLegReference() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransportLegReference
}

// GetTransportLegReferenceOk returns a tuple with the TransportLegReference field value
// and a boolean to check if the value has been set.
func (o *TransportEquipmentEventAllOf) GetTransportLegReferenceOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.TransportLegReference, true
}

// SetTransportLegReference sets field value
func (o *TransportEquipmentEventAllOf) SetTransportLegReference(v string) {
	o.TransportLegReference = v
}

// GetEquipmentReference returns the EquipmentReference field value if set, zero value otherwise.
func (o *TransportEquipmentEventAllOf) GetEquipmentReference() string {
	if o == nil || o.EquipmentReference == nil {
		var ret string
		return ret
	}
	return *o.EquipmentReference
}

// GetEquipmentReferenceOk returns a tuple with the EquipmentReference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportEquipmentEventAllOf) GetEquipmentReferenceOk() (*string, bool) {
	if o == nil || o.EquipmentReference == nil {
		return nil, false
	}
	return o.EquipmentReference, true
}

// HasEquipmentReference returns a boolean if a field has been set.
func (o *TransportEquipmentEventAllOf) HasEquipmentReference() bool {
	if o != nil && o.EquipmentReference != nil {
		return true
	}

	return false
}

// SetEquipmentReference gets a reference to the given string and assigns it to the EquipmentReference field.
func (o *TransportEquipmentEventAllOf) SetEquipmentReference(v string) {
	o.EquipmentReference = &v
}

// GetFacilityTypeCode returns the FacilityTypeCode field value
func (o *TransportEquipmentEventAllOf) GetFacilityTypeCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FacilityTypeCode
}

// GetFacilityTypeCodeOk returns a tuple with the FacilityTypeCode field value
// and a boolean to check if the value has been set.
func (o *TransportEquipmentEventAllOf) GetFacilityTypeCodeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.FacilityTypeCode, true
}

// SetFacilityTypeCode sets field value
func (o *TransportEquipmentEventAllOf) SetFacilityTypeCode(v string) {
	o.FacilityTypeCode = v
}

// GetUNLocationCode returns the UNLocationCode field value
func (o *TransportEquipmentEventAllOf) GetUNLocationCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UNLocationCode
}

// GetUNLocationCodeOk returns a tuple with the UNLocationCode field value
// and a boolean to check if the value has been set.
func (o *TransportEquipmentEventAllOf) GetUNLocationCodeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.UNLocationCode, true
}

// SetUNLocationCode sets field value
func (o *TransportEquipmentEventAllOf) SetUNLocationCode(v string) {
	o.UNLocationCode = v
}

// GetFacilityCode returns the FacilityCode field value
func (o *TransportEquipmentEventAllOf) GetFacilityCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FacilityCode
}

// GetFacilityCodeOk returns a tuple with the FacilityCode field value
// and a boolean to check if the value has been set.
func (o *TransportEquipmentEventAllOf) GetFacilityCodeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.FacilityCode, true
}

// SetFacilityCode sets field value
func (o *TransportEquipmentEventAllOf) SetFacilityCode(v string) {
	o.FacilityCode = v
}

// GetOtherFacility returns the OtherFacility field value if set, zero value otherwise.
func (o *TransportEquipmentEventAllOf) GetOtherFacility() string {
	if o == nil || o.OtherFacility == nil {
		var ret string
		return ret
	}
	return *o.OtherFacility
}

// GetOtherFacilityOk returns a tuple with the OtherFacility field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportEquipmentEventAllOf) GetOtherFacilityOk() (*string, bool) {
	if o == nil || o.OtherFacility == nil {
		return nil, false
	}
	return o.OtherFacility, true
}

// HasOtherFacility returns a boolean if a field has been set.
func (o *TransportEquipmentEventAllOf) HasOtherFacility() bool {
	if o != nil && o.OtherFacility != nil {
		return true
	}

	return false
}

// SetOtherFacility gets a reference to the given string and assigns it to the OtherFacility field.
func (o *TransportEquipmentEventAllOf) SetOtherFacility(v string) {
	o.OtherFacility = &v
}

// GetEmptyIndicatorCode returns the EmptyIndicatorCode field value
func (o *TransportEquipmentEventAllOf) GetEmptyIndicatorCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EmptyIndicatorCode
}

// GetEmptyIndicatorCodeOk returns a tuple with the EmptyIndicatorCode field value
// and a boolean to check if the value has been set.
func (o *TransportEquipmentEventAllOf) GetEmptyIndicatorCodeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.EmptyIndicatorCode, true
}

// SetEmptyIndicatorCode sets field value
func (o *TransportEquipmentEventAllOf) SetEmptyIndicatorCode(v string) {
	o.EmptyIndicatorCode = v
}

// GetModeOfTransportCode returns the ModeOfTransportCode field value if set, zero value otherwise.
func (o *TransportEquipmentEventAllOf) GetModeOfTransportCode() int32 {
	if o == nil || o.ModeOfTransportCode == nil {
		var ret int32
		return ret
	}
	return *o.ModeOfTransportCode
}

// GetModeOfTransportCodeOk returns a tuple with the ModeOfTransportCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransportEquipmentEventAllOf) GetModeOfTransportCodeOk() (*int32, bool) {
	if o == nil || o.ModeOfTransportCode == nil {
		return nil, false
	}
	return o.ModeOfTransportCode, true
}

// HasModeOfTransportCode returns a boolean if a field has been set.
func (o *TransportEquipmentEventAllOf) HasModeOfTransportCode() bool {
	if o != nil && o.ModeOfTransportCode != nil {
		return true
	}

	return false
}

// SetModeOfTransportCode gets a reference to the given int32 and assigns it to the ModeOfTransportCode field.
func (o *TransportEquipmentEventAllOf) SetModeOfTransportCode(v int32) {
	o.ModeOfTransportCode = &v
}

func (o TransportEquipmentEventAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.EventType != nil {
		toSerialize["eventType"] = o.EventType
	}
	if true {
		toSerialize["transportReference"] = o.TransportReference
	}
	if true {
		toSerialize["transportLegReference"] = o.TransportLegReference
	}
	if o.EquipmentReference != nil {
		toSerialize["equipmentReference"] = o.EquipmentReference
	}
	if true {
		toSerialize["facilityTypeCode"] = o.FacilityTypeCode
	}
	if true {
		toSerialize["UNLocationCode"] = o.UNLocationCode
	}
	if true {
		toSerialize["facilityCode"] = o.FacilityCode
	}
	if o.OtherFacility != nil {
		toSerialize["otherFacility"] = o.OtherFacility
	}
	if true {
		toSerialize["emptyIndicatorCode"] = o.EmptyIndicatorCode
	}
	if o.ModeOfTransportCode != nil {
		toSerialize["modeOfTransportCode"] = o.ModeOfTransportCode
	}
	return json.Marshal(toSerialize)
}

type NullableTransportEquipmentEventAllOf struct {
	value *TransportEquipmentEventAllOf
	isSet bool
}

func (v NullableTransportEquipmentEventAllOf) Get() *TransportEquipmentEventAllOf {
	return v.value
}

func (v *NullableTransportEquipmentEventAllOf) Set(val *TransportEquipmentEventAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableTransportEquipmentEventAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableTransportEquipmentEventAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransportEquipmentEventAllOf(val *TransportEquipmentEventAllOf) *NullableTransportEquipmentEventAllOf {
	return &NullableTransportEquipmentEventAllOf{value: val, isSet: true}
}

func (v NullableTransportEquipmentEventAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransportEquipmentEventAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


