/*
ONE Specification for DCSA Track & Trace API v2.2

  # DCSA Track and Trace v2.2    **Overview:**    The **DCSA Track and Trace v2.2 API** provides a standardized and reliable mechanism for tracking container movements throughout the global shipping network. It is designed to align with the Digital Container Shipping Association (DCSA) standards, promoting **interoperability** between carriers, shippers, and third-party logistics providers.    This API allows stakeholders to monitor the **end-to-end journey** of containers, offering insights into key milestones such as:  - **Vessel arrivals**  - **Departures**  - **Equipment loading**  - **Transport events**    By delivering **uniform tracking data** across various carriers and ports, this API reduces manual processes and improves operational efficiency for managing large-scale shipping operations.    ---    ## Key Features:    ### 1. **Event Standardization**    All events related to container transport are defined according to DCSA standards, ensuring consistent terminology and reporting across the entire logistics chain.    ### 2. **On-Demand Data Retrieval**    Customers can pull **up-to-date information** about container locations, equipment status, and shipment events when needed, enabling timely and informed decision-making.    ### 3. **Seamless Integration**    Designed to integrate easily with existing systems, the API offers flexibility for users who manage large-scale shipments or have evolving logistics requirements.    ### 4. **Scalability**    Whether tracking a few containers or managing thousands, the API is optimized to handle **large datasets efficiently**, ensuring timely access to critical shipping information.    ---    ### Conclusion:    The **DCSA Track and Trace v2.2 API** empowers companies to enhance their visibility into global logistics operations, improve communication between parties, and drive better service outcomes through transparency and **real-time information sharing**.

API version: 2.2
Contact: integration.support@one-line.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package one

import (
	"encoding/json"
	"fmt"
)

// FacilityCodeListProvider The provider used for identifying the facility Code
type FacilityCodeListProvider string

// List of facilityCodeListProvider
const (
	FCLP_BIC  FacilityCodeListProvider = "BIC"
	FCLP_SMDG FacilityCodeListProvider = "SMDG"
)

// All allowed values of FacilityCodeListProvider enum
var AllowedFacilityCodeListProviderEnumValues = []FacilityCodeListProvider{
	"BIC",
	"SMDG",
}

func (v *FacilityCodeListProvider) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := FacilityCodeListProvider(value)
	for _, existing := range AllowedFacilityCodeListProviderEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid FacilityCodeListProvider", value)
}

// NewFacilityCodeListProviderFromValue returns a pointer to a valid FacilityCodeListProvider
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewFacilityCodeListProviderFromValue(v string) (*FacilityCodeListProvider, error) {
	ev := FacilityCodeListProvider(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for FacilityCodeListProvider: valid values are %v", v, AllowedFacilityCodeListProviderEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v FacilityCodeListProvider) IsValid() bool {
	for _, existing := range AllowedFacilityCodeListProviderEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to facilityCodeListProvider value
func (v FacilityCodeListProvider) Ptr() *FacilityCodeListProvider {
	return &v
}

type NullableFacilityCodeListProvider struct {
	value *FacilityCodeListProvider
	isSet bool
}

func (v NullableFacilityCodeListProvider) Get() *FacilityCodeListProvider {
	return v.value
}

func (v *NullableFacilityCodeListProvider) Set(val *FacilityCodeListProvider) {
	v.value = val
	v.isSet = true
}

func (v NullableFacilityCodeListProvider) IsSet() bool {
	return v.isSet
}

func (v *NullableFacilityCodeListProvider) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFacilityCodeListProvider(val *FacilityCodeListProvider) *NullableFacilityCodeListProvider {
	return &NullableFacilityCodeListProvider{value: val, isSet: true}
}

func (v NullableFacilityCodeListProvider) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFacilityCodeListProvider) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
