/*
ONE Specification for DCSA Track & Trace API v2.2

  # DCSA Track and Trace v2.2    **Overview:**    The **DCSA Track and Trace v2.2 API** provides a standardized and reliable mechanism for tracking container movements throughout the global shipping network. It is designed to align with the Digital Container Shipping Association (DCSA) standards, promoting **interoperability** between carriers, shippers, and third-party logistics providers.    This API allows stakeholders to monitor the **end-to-end journey** of containers, offering insights into key milestones such as:  - **Vessel arrivals**  - **Departures**  - **Equipment loading**  - **Transport events**    By delivering **uniform tracking data** across various carriers and ports, this API reduces manual processes and improves operational efficiency for managing large-scale shipping operations.    ---    ## Key Features:    ### 1. **Event Standardization**    All events related to container transport are defined according to DCSA standards, ensuring consistent terminology and reporting across the entire logistics chain.    ### 2. **On-Demand Data Retrieval**    Customers can pull **up-to-date information** about container locations, equipment status, and shipment events when needed, enabling timely and informed decision-making.    ### 3. **Seamless Integration**    Designed to integrate easily with existing systems, the API offers flexibility for users who manage large-scale shipments or have evolving logistics requirements.    ### 4. **Scalability**    Whether tracking a few containers or managing thousands, the API is optimized to handle **large datasets efficiently**, ensuring timely access to critical shipping information.    ---    ### Conclusion:    The **DCSA Track and Trace v2.2 API** empowers companies to enhance their visibility into global logistics operations, improve communication between parties, and drive better service outcomes through transparency and **real-time information sharing**.

API version: 2.2
Contact: integration.support@one-line.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package one

import (
	"encoding/json"
	"fmt"
)

// SealSource The source of the seal, namely who has affixed the seal. This attribute links to the Seal Source ID defined in the Seal Source reference data entity. - CAR (Carrier) - SHI (Shipper) - PHY (Phytosanitary) - VET (Veterinary) - CUS (Customs)
type SealSource string

// List of sealSource
const (
	CAR SealSource = "CAR"
	SHI SealSource = "SHI"
	PHY SealSource = "PHY"
	VET SealSource = "VET"
	CUS SealSource = "CUS"
)

// All allowed values of SealSource enum
var AllowedSealSourceEnumValues = []SealSource{
	"CAR",
	"SHI",
	"PHY",
	"VET",
	"CUS",
}

func (v *SealSource) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SealSource(value)
	for _, existing := range AllowedSealSourceEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SealSource", value)
}

// NewSealSourceFromValue returns a pointer to a valid SealSource
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSealSourceFromValue(v string) (*SealSource, error) {
	ev := SealSource(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SealSource: valid values are %v", v, AllowedSealSourceEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SealSource) IsValid() bool {
	for _, existing := range AllowedSealSourceEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to sealSource value
func (v SealSource) Ptr() *SealSource {
	return &v
}

type NullableSealSource struct {
	value *SealSource
	isSet bool
}

func (v NullableSealSource) Get() *SealSource {
	return v.value
}

func (v *NullableSealSource) Set(val *SealSource) {
	v.value = val
	v.isSet = true
}

func (v NullableSealSource) IsSet() bool {
	return v.isSet
}

func (v *NullableSealSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSealSource(val *SealSource) *NullableSealSource {
	return &NullableSealSource{value: val, isSet: true}
}

func (v NullableSealSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSealSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
