/*
ONE Specification for DCSA Track & Trace API v2.2

  # DCSA Track and Trace v2.2    **Overview:**    The **DCSA Track and Trace v2.2 API** provides a standardized and reliable mechanism for tracking container movements throughout the global shipping network. It is designed to align with the Digital Container Shipping Association (DCSA) standards, promoting **interoperability** between carriers, shippers, and third-party logistics providers.    This API allows stakeholders to monitor the **end-to-end journey** of containers, offering insights into key milestones such as:  - **Vessel arrivals**  - **Departures**  - **Equipment loading**  - **Transport events**    By delivering **uniform tracking data** across various carriers and ports, this API reduces manual processes and improves operational efficiency for managing large-scale shipping operations.    ---    ## Key Features:    ### 1. **Event Standardization**    All events related to container transport are defined according to DCSA standards, ensuring consistent terminology and reporting across the entire logistics chain.    ### 2. **On-Demand Data Retrieval**    Customers can pull **up-to-date information** about container locations, equipment status, and shipment events when needed, enabling timely and informed decision-making.    ### 3. **Seamless Integration**    Designed to integrate easily with existing systems, the API offers flexibility for users who manage large-scale shipments or have evolving logistics requirements.    ### 4. **Scalability**    Whether tracking a few containers or managing thousands, the API is optimized to handle **large datasets efficiently**, ensuring timely access to critical shipping information.    ---    ### Conclusion:    The **DCSA Track and Trace v2.2 API** empowers companies to enhance their visibility into global logistics operations, improve communication between parties, and drive better service outcomes through transparency and **real-time information sharing**.

API version: 2.2
Contact: integration.support@one-line.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package one

import (
	"encoding/json"
)

// checks if the InlineResponse200 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InlineResponse200{}

// InlineResponse200 struct for InlineResponse200
type InlineResponse200 struct {
	RefreshTokenExpiresIn *string `json:"refresh_token_expires_in,omitempty"`
	ApiProductList        *string `json:"api_product_list,omitempty"`
	ApiProductListJson    *string `json:"api_product_list_json,omitempty"`
	OrganizationName      *string `json:"organization_name,omitempty"`
	DeveloperEmail        *string `json:"developer.email,omitempty"`
	TokenType             *string `json:"token_type,omitempty"`
	IssuedAt              *string `json:"issued_at,omitempty"`
	ClientId              *string `json:"client_id,omitempty"`
	AccessToken           *string `json:"access_token,omitempty"`
	ApplicationName       *string `json:"application_name,omitempty"`
	Scope                 *string `json:"scope,omitempty"`
	ExpiresIn             *string `json:"expires_in,omitempty"`
	RefreshCount          *string `json:"refresh_count,omitempty"`
	Status                *string `json:"status,omitempty"`
}

// NewInlineResponse200 instantiates a new InlineResponse200 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse200() *InlineResponse200 {
	this := InlineResponse200{}
	return &this
}

// NewInlineResponse200WithDefaults instantiates a new InlineResponse200 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse200WithDefaults() *InlineResponse200 {
	this := InlineResponse200{}
	return &this
}

// GetRefreshTokenExpiresIn returns the RefreshTokenExpiresIn field value if set, zero value otherwise.
func (o *InlineResponse200) GetRefreshTokenExpiresIn() string {
	if o == nil || IsNil(o.RefreshTokenExpiresIn) {
		var ret string
		return ret
	}
	return *o.RefreshTokenExpiresIn
}

// GetRefreshTokenExpiresInOk returns a tuple with the RefreshTokenExpiresIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetRefreshTokenExpiresInOk() (*string, bool) {
	if o == nil || IsNil(o.RefreshTokenExpiresIn) {
		return nil, false
	}
	return o.RefreshTokenExpiresIn, true
}

// HasRefreshTokenExpiresIn returns a boolean if a field has been set.
func (o *InlineResponse200) HasRefreshTokenExpiresIn() bool {
	if o != nil && !IsNil(o.RefreshTokenExpiresIn) {
		return true
	}

	return false
}

// SetRefreshTokenExpiresIn gets a reference to the given string and assigns it to the RefreshTokenExpiresIn field.
func (o *InlineResponse200) SetRefreshTokenExpiresIn(v string) {
	o.RefreshTokenExpiresIn = &v
}

// GetApiProductList returns the ApiProductList field value if set, zero value otherwise.
func (o *InlineResponse200) GetApiProductList() string {
	if o == nil || IsNil(o.ApiProductList) {
		var ret string
		return ret
	}
	return *o.ApiProductList
}

// GetApiProductListOk returns a tuple with the ApiProductList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetApiProductListOk() (*string, bool) {
	if o == nil || IsNil(o.ApiProductList) {
		return nil, false
	}
	return o.ApiProductList, true
}

// HasApiProductList returns a boolean if a field has been set.
func (o *InlineResponse200) HasApiProductList() bool {
	if o != nil && !IsNil(o.ApiProductList) {
		return true
	}

	return false
}

// SetApiProductList gets a reference to the given string and assigns it to the ApiProductList field.
func (o *InlineResponse200) SetApiProductList(v string) {
	o.ApiProductList = &v
}

// GetApiProductListJson returns the ApiProductListJson field value if set, zero value otherwise.
func (o *InlineResponse200) GetApiProductListJson() string {
	if o == nil || IsNil(o.ApiProductListJson) {
		var ret string
		return ret
	}
	return *o.ApiProductListJson
}

// GetApiProductListJsonOk returns a tuple with the ApiProductListJson field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetApiProductListJsonOk() (*string, bool) {
	if o == nil || IsNil(o.ApiProductListJson) {
		return nil, false
	}
	return o.ApiProductListJson, true
}

// HasApiProductListJson returns a boolean if a field has been set.
func (o *InlineResponse200) HasApiProductListJson() bool {
	if o != nil && !IsNil(o.ApiProductListJson) {
		return true
	}

	return false
}

// SetApiProductListJson gets a reference to the given string and assigns it to the ApiProductListJson field.
func (o *InlineResponse200) SetApiProductListJson(v string) {
	o.ApiProductListJson = &v
}

// GetOrganizationName returns the OrganizationName field value if set, zero value otherwise.
func (o *InlineResponse200) GetOrganizationName() string {
	if o == nil || IsNil(o.OrganizationName) {
		var ret string
		return ret
	}
	return *o.OrganizationName
}

// GetOrganizationNameOk returns a tuple with the OrganizationName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetOrganizationNameOk() (*string, bool) {
	if o == nil || IsNil(o.OrganizationName) {
		return nil, false
	}
	return o.OrganizationName, true
}

// HasOrganizationName returns a boolean if a field has been set.
func (o *InlineResponse200) HasOrganizationName() bool {
	if o != nil && !IsNil(o.OrganizationName) {
		return true
	}

	return false
}

// SetOrganizationName gets a reference to the given string and assigns it to the OrganizationName field.
func (o *InlineResponse200) SetOrganizationName(v string) {
	o.OrganizationName = &v
}

// GetDeveloperEmail returns the DeveloperEmail field value if set, zero value otherwise.
func (o *InlineResponse200) GetDeveloperEmail() string {
	if o == nil || IsNil(o.DeveloperEmail) {
		var ret string
		return ret
	}
	return *o.DeveloperEmail
}

// GetDeveloperEmailOk returns a tuple with the DeveloperEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetDeveloperEmailOk() (*string, bool) {
	if o == nil || IsNil(o.DeveloperEmail) {
		return nil, false
	}
	return o.DeveloperEmail, true
}

// HasDeveloperEmail returns a boolean if a field has been set.
func (o *InlineResponse200) HasDeveloperEmail() bool {
	if o != nil && !IsNil(o.DeveloperEmail) {
		return true
	}

	return false
}

// SetDeveloperEmail gets a reference to the given string and assigns it to the DeveloperEmail field.
func (o *InlineResponse200) SetDeveloperEmail(v string) {
	o.DeveloperEmail = &v
}

// GetTokenType returns the TokenType field value if set, zero value otherwise.
func (o *InlineResponse200) GetTokenType() string {
	if o == nil || IsNil(o.TokenType) {
		var ret string
		return ret
	}
	return *o.TokenType
}

// GetTokenTypeOk returns a tuple with the TokenType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetTokenTypeOk() (*string, bool) {
	if o == nil || IsNil(o.TokenType) {
		return nil, false
	}
	return o.TokenType, true
}

// HasTokenType returns a boolean if a field has been set.
func (o *InlineResponse200) HasTokenType() bool {
	if o != nil && !IsNil(o.TokenType) {
		return true
	}

	return false
}

// SetTokenType gets a reference to the given string and assigns it to the TokenType field.
func (o *InlineResponse200) SetTokenType(v string) {
	o.TokenType = &v
}

// GetIssuedAt returns the IssuedAt field value if set, zero value otherwise.
func (o *InlineResponse200) GetIssuedAt() string {
	if o == nil || IsNil(o.IssuedAt) {
		var ret string
		return ret
	}
	return *o.IssuedAt
}

// GetIssuedAtOk returns a tuple with the IssuedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetIssuedAtOk() (*string, bool) {
	if o == nil || IsNil(o.IssuedAt) {
		return nil, false
	}
	return o.IssuedAt, true
}

// HasIssuedAt returns a boolean if a field has been set.
func (o *InlineResponse200) HasIssuedAt() bool {
	if o != nil && !IsNil(o.IssuedAt) {
		return true
	}

	return false
}

// SetIssuedAt gets a reference to the given string and assigns it to the IssuedAt field.
func (o *InlineResponse200) SetIssuedAt(v string) {
	o.IssuedAt = &v
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *InlineResponse200) GetClientId() string {
	if o == nil || IsNil(o.ClientId) {
		var ret string
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetClientIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClientId) {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *InlineResponse200) HasClientId() bool {
	if o != nil && !IsNil(o.ClientId) {
		return true
	}

	return false
}

// SetClientId gets a reference to the given string and assigns it to the ClientId field.
func (o *InlineResponse200) SetClientId(v string) {
	o.ClientId = &v
}

// GetAccessToken returns the AccessToken field value if set, zero value otherwise.
func (o *InlineResponse200) GetAccessToken() string {
	if o == nil || IsNil(o.AccessToken) {
		var ret string
		return ret
	}
	return *o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetAccessTokenOk() (*string, bool) {
	if o == nil || IsNil(o.AccessToken) {
		return nil, false
	}
	return o.AccessToken, true
}

// HasAccessToken returns a boolean if a field has been set.
func (o *InlineResponse200) HasAccessToken() bool {
	if o != nil && !IsNil(o.AccessToken) {
		return true
	}

	return false
}

// SetAccessToken gets a reference to the given string and assigns it to the AccessToken field.
func (o *InlineResponse200) SetAccessToken(v string) {
	o.AccessToken = &v
}

// GetApplicationName returns the ApplicationName field value if set, zero value otherwise.
func (o *InlineResponse200) GetApplicationName() string {
	if o == nil || IsNil(o.ApplicationName) {
		var ret string
		return ret
	}
	return *o.ApplicationName
}

// GetApplicationNameOk returns a tuple with the ApplicationName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetApplicationNameOk() (*string, bool) {
	if o == nil || IsNil(o.ApplicationName) {
		return nil, false
	}
	return o.ApplicationName, true
}

// HasApplicationName returns a boolean if a field has been set.
func (o *InlineResponse200) HasApplicationName() bool {
	if o != nil && !IsNil(o.ApplicationName) {
		return true
	}

	return false
}

// SetApplicationName gets a reference to the given string and assigns it to the ApplicationName field.
func (o *InlineResponse200) SetApplicationName(v string) {
	o.ApplicationName = &v
}

// GetScope returns the Scope field value if set, zero value otherwise.
func (o *InlineResponse200) GetScope() string {
	if o == nil || IsNil(o.Scope) {
		var ret string
		return ret
	}
	return *o.Scope
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetScopeOk() (*string, bool) {
	if o == nil || IsNil(o.Scope) {
		return nil, false
	}
	return o.Scope, true
}

// HasScope returns a boolean if a field has been set.
func (o *InlineResponse200) HasScope() bool {
	if o != nil && !IsNil(o.Scope) {
		return true
	}

	return false
}

// SetScope gets a reference to the given string and assigns it to the Scope field.
func (o *InlineResponse200) SetScope(v string) {
	o.Scope = &v
}

// GetExpiresIn returns the ExpiresIn field value if set, zero value otherwise.
func (o *InlineResponse200) GetExpiresIn() string {
	if o == nil || IsNil(o.ExpiresIn) {
		var ret string
		return ret
	}
	return *o.ExpiresIn
}

// GetExpiresInOk returns a tuple with the ExpiresIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetExpiresInOk() (*string, bool) {
	if o == nil || IsNil(o.ExpiresIn) {
		return nil, false
	}
	return o.ExpiresIn, true
}

// HasExpiresIn returns a boolean if a field has been set.
func (o *InlineResponse200) HasExpiresIn() bool {
	if o != nil && !IsNil(o.ExpiresIn) {
		return true
	}

	return false
}

// SetExpiresIn gets a reference to the given string and assigns it to the ExpiresIn field.
func (o *InlineResponse200) SetExpiresIn(v string) {
	o.ExpiresIn = &v
}

// GetRefreshCount returns the RefreshCount field value if set, zero value otherwise.
func (o *InlineResponse200) GetRefreshCount() string {
	if o == nil || IsNil(o.RefreshCount) {
		var ret string
		return ret
	}
	return *o.RefreshCount
}

// GetRefreshCountOk returns a tuple with the RefreshCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetRefreshCountOk() (*string, bool) {
	if o == nil || IsNil(o.RefreshCount) {
		return nil, false
	}
	return o.RefreshCount, true
}

// HasRefreshCount returns a boolean if a field has been set.
func (o *InlineResponse200) HasRefreshCount() bool {
	if o != nil && !IsNil(o.RefreshCount) {
		return true
	}

	return false
}

// SetRefreshCount gets a reference to the given string and assigns it to the RefreshCount field.
func (o *InlineResponse200) SetRefreshCount(v string) {
	o.RefreshCount = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *InlineResponse200) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *InlineResponse200) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *InlineResponse200) SetStatus(v string) {
	o.Status = &v
}

func (o InlineResponse200) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InlineResponse200) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RefreshTokenExpiresIn) {
		toSerialize["refresh_token_expires_in"] = o.RefreshTokenExpiresIn
	}
	if !IsNil(o.ApiProductList) {
		toSerialize["api_product_list"] = o.ApiProductList
	}
	if !IsNil(o.ApiProductListJson) {
		toSerialize["api_product_list_json"] = o.ApiProductListJson
	}
	if !IsNil(o.OrganizationName) {
		toSerialize["organization_name"] = o.OrganizationName
	}
	if !IsNil(o.DeveloperEmail) {
		toSerialize["developer.email"] = o.DeveloperEmail
	}
	if !IsNil(o.TokenType) {
		toSerialize["token_type"] = o.TokenType
	}
	if !IsNil(o.IssuedAt) {
		toSerialize["issued_at"] = o.IssuedAt
	}
	if !IsNil(o.ClientId) {
		toSerialize["client_id"] = o.ClientId
	}
	if !IsNil(o.AccessToken) {
		toSerialize["access_token"] = o.AccessToken
	}
	if !IsNil(o.ApplicationName) {
		toSerialize["application_name"] = o.ApplicationName
	}
	if !IsNil(o.Scope) {
		toSerialize["scope"] = o.Scope
	}
	if !IsNil(o.ExpiresIn) {
		toSerialize["expires_in"] = o.ExpiresIn
	}
	if !IsNil(o.RefreshCount) {
		toSerialize["refresh_count"] = o.RefreshCount
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableInlineResponse200 struct {
	value *InlineResponse200
	isSet bool
}

func (v NullableInlineResponse200) Get() *InlineResponse200 {
	return v.value
}

func (v *NullableInlineResponse200) Set(val *InlineResponse200) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse200) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse200) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse200(val *InlineResponse200) *NullableInlineResponse200 {
	return &NullableInlineResponse200{value: val, isSet: true}
}

func (v NullableInlineResponse200) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse200) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
