/*
ONE CARGO TRACKING API

Cargo tacking details is provided based on DCSA standards. (1.2)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package one

import (
	"encoding/json"
)

// ShipmentEventAllOf struct for ShipmentEventAllOf
type ShipmentEventAllOf struct {
	EventType *string `json:"eventType,omitempty"`
	// The code to identify the type of information that is related to the shipment.
	ShipmentInformationTypeCode string `json:"shipmentInformationTypeCode"`
}

// NewShipmentEventAllOf instantiates a new ShipmentEventAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShipmentEventAllOf(shipmentInformationTypeCode string) *ShipmentEventAllOf {
	this := ShipmentEventAllOf{}
	this.ShipmentInformationTypeCode = shipmentInformationTypeCode
	return &this
}

// NewShipmentEventAllOfWithDefaults instantiates a new ShipmentEventAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShipmentEventAllOfWithDefaults() *ShipmentEventAllOf {
	this := ShipmentEventAllOf{}
	return &this
}

// GetEventType returns the EventType field value if set, zero value otherwise.
func (o *ShipmentEventAllOf) GetEventType() string {
	if o == nil || o.EventType == nil {
		var ret string
		return ret
	}
	return *o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShipmentEventAllOf) GetEventTypeOk() (*string, bool) {
	if o == nil || o.EventType == nil {
		return nil, false
	}
	return o.EventType, true
}

// HasEventType returns a boolean if a field has been set.
func (o *ShipmentEventAllOf) HasEventType() bool {
	if o != nil && o.EventType != nil {
		return true
	}

	return false
}

// SetEventType gets a reference to the given string and assigns it to the EventType field.
func (o *ShipmentEventAllOf) SetEventType(v string) {
	o.EventType = &v
}

// GetShipmentInformationTypeCode returns the ShipmentInformationTypeCode field value
func (o *ShipmentEventAllOf) GetShipmentInformationTypeCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ShipmentInformationTypeCode
}

// GetShipmentInformationTypeCodeOk returns a tuple with the ShipmentInformationTypeCode field value
// and a boolean to check if the value has been set.
func (o *ShipmentEventAllOf) GetShipmentInformationTypeCodeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ShipmentInformationTypeCode, true
}

// SetShipmentInformationTypeCode sets field value
func (o *ShipmentEventAllOf) SetShipmentInformationTypeCode(v string) {
	o.ShipmentInformationTypeCode = v
}

func (o ShipmentEventAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.EventType != nil {
		toSerialize["eventType"] = o.EventType
	}
	if true {
		toSerialize["shipmentInformationTypeCode"] = o.ShipmentInformationTypeCode
	}
	return json.Marshal(toSerialize)
}

type NullableShipmentEventAllOf struct {
	value *ShipmentEventAllOf
	isSet bool
}

func (v NullableShipmentEventAllOf) Get() *ShipmentEventAllOf {
	return v.value
}

func (v *NullableShipmentEventAllOf) Set(val *ShipmentEventAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableShipmentEventAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableShipmentEventAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShipmentEventAllOf(val *ShipmentEventAllOf) *NullableShipmentEventAllOf {
	return &NullableShipmentEventAllOf{value: val, isSet: true}
}

func (v NullableShipmentEventAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShipmentEventAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


